# ============================================================================
# new-cuda-project.ps1   (single-file edition)
# ----------------------------------------------------------------------------
# One-shot bootstrap for a CUDA C++ project on a Sussex lab Windows machine.
#
# Student workflow:
#     .\new-cuda-project.ps1 -Name my-first-kernel
#
# What it does, in order:
#   1. Validates the project name.
#   2. Checks WSL is enabled on this machine (fails fast with IT message if not).
#   3. Ensures the "LabGPU" WSL distro exists; provisions it if absent.
#   4. Ensures the CUDA toolkit is installed inside LabGPU; installs if absent.
#   5. Creates the project folder + writes all template files inside WSL.
#   6. Opens the project in VS Code via WSL-remote.
#
# This single-file version embeds all bash scripts and template files as
# here-strings. They are extracted to a temporary directory at run time,
# pushed into WSL with correct (LF) line endings, and executed.
#
# Re-running with the same name is safe: the script is idempotent up to
# step 5, where it refuses to overwrite an existing project unless -Force.
#
# Why WSL? CUDA C++ on Windows needs MSVC as the host compiler, and MSVC
# needs Visual Studio (admin). WSL sidesteps that — apt installs the toolkit
# user-mode and g++ is the host compiler. The only one-time admin step is
# enabling WSL itself (IT runs `wsl --install --no-distribution` once per
# machine); after that, students provision distros + install CUDA bits
# entirely user-mode.
#
# Prerequisites (one-time, done by IT, with admin rights):
#   - WSL enabled:   wsl --install --no-distribution    (then reboot)
#   - NVIDIA Windows driver with WSL passthrough (any post-2021 driver)
#   - VS Code installed (user-mode installer is fine, no admin needed)
#
# ----------------------------------------------------------------------------
# THIS FILE IS GENERATED BY build.ps1 FROM script-template.ps1 + template/.
# Do not edit the distributed script directly — edit the sources and rebuild.
# ============================================================================

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Name,

    [Parameter()]
    [ValidateSet('cuda')]
    [string]$Type = 'cuda',

    [Parameter()]
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# ============================================================================
# CONFIGURATION
# ============================================================================

$DistroName        = 'LabGPU'
$DistroInstallDir  = Join-Path $env:LOCALAPPDATA "WSL\$DistroName"
$DistroTarballURL  = 'https://cloud-images.ubuntu.com/wsl/jammy/current/ubuntu-jammy-wsl-amd64-ubuntu22.04lts.rootfs.tar.gz'
$CudaToolkitVer    = '12.8'   # major.minor — apt package name is cuda-toolkit-12-8
$ProjectsRoot      = 'projects'

# ============================================================================
# EMBEDDED FILES
# ----------------------------------------------------------------------------
# Each $E_* is the literal content of a file we'll write out at run time.
# Single-quoted here-strings (@'...'@) preserve everything literally — no
# variable interpolation, no escaping of $ or `. Placeholders like
# __PROJECT_NAME__ are substituted on the Linux side by sed.
#
# The here-strings below are populated at build time by build.ps1 from the
# files in linux/ and template/. The {{TEMPLATE: ...}} markers are the
# build's hook.
# ============================================================================

# {{TEMPLATE: $E_bootstrap_distro = linux/bootstrap-distro.sh}}

# {{TEMPLATE: $E_ensure_cuda = linux/ensure-cuda.sh}}

# {{TEMPLATE: $E_make_project = linux/make-project.sh}}

# {{TEMPLATE: $E_cmakelists = template/CMakeLists.txt}}

# {{TEMPLATE: $E_main_cu = template/main.cu}}

# {{TEMPLATE: $E_gitignore = template/.gitignore}}

# {{TEMPLATE: $E_readme = template/README.md}}

# {{TEMPLATE: $E_vscode_settings = template/.vscode/settings.json}}

# {{TEMPLATE: $E_vscode_extensions = template/.vscode/extensions.json}}

# {{TEMPLATE: $E_vscode_tasks = template/.vscode/tasks.json}}

# {{TEMPLATE: $E_vscode_launch = template/.vscode/launch.json}}

# ============================================================================
# HELPERS
# ============================================================================

function Write-Step  { param($Msg) Write-Host "==> $Msg" -ForegroundColor Cyan }
function Write-Ok    { param($Msg) Write-Host "    $Msg" -ForegroundColor Green }
function Write-Warn2 { param($Msg) Write-Host "    $Msg" -ForegroundColor Yellow }
function Write-Err   { param($Msg) Write-Host "[!] $Msg" -ForegroundColor Red }

function Write-LfFile {
    # Writes content to a file with Unix (LF) line endings, no BOM.
    # Critical for any file destined for bash inside WSL.
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] [string]$Content
    )
    $lf = $Content -replace "`r`n", "`n"
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $lf, $utf8NoBom)
}

function Test-WslEnabled {
    try {
        $null = & wsl.exe --status 2>$null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Test-DistroExists {
    param([string]$DistroName)
    $distros = & wsl.exe --list --quiet 2>$null |
               ForEach-Object { $_ -replace "`0", "" } |
               Where-Object { $_ -and $_.Trim() } |
               ForEach-Object { $_.Trim() }
    return $distros -contains $DistroName
}

function Invoke-WslBash {
    # Runs a bash command inside the distro and returns its stdout as a single
    # string (LF-joined, trimmed of trailing newline).
    #
    # Notes on the redirection dance:
    #   - We capture stderr to a temp file rather than using `2>&1`. In Windows
    #     PowerShell 5.1, `2>&1` on a native exe wraps each stderr line in an
    #     ErrorRecord and pollutes the returned array, which breaks any caller
    #     that wants to use the stdout as a plain string.
    #   - We default to `bash -c` (no `-l`) so login chatter from /etc/profile
    #     and ~/.bashrc doesn't contaminate the output. Pass -Login when the
    #     command needs the user's interactive environment (e.g. conda on PATH).
    param(
        [Parameter(Mandatory)] [string]$Command,
        [switch]$AsRoot,
        [switch]$Login
    )
    $userArgs  = if ($AsRoot) { @('-u', 'root') } else { @() }
    $bashFlags = if ($Login)  { '-lc' } else { '-c' }
    $allArgs   = @('-d', $DistroName) + $userArgs + @('--', 'bash', $bashFlags, $Command)

    $stderrFile = [System.IO.Path]::GetTempFileName()
    try {
        $stdout = & wsl.exe @allArgs 2>$stderrFile
        $exit   = $LASTEXITCODE
        $stderr = if (Test-Path $stderrFile) { Get-Content $stderrFile -Raw } else { '' }

        if ($exit -ne 0) {
            $stdoutStr = ($stdout | ForEach-Object { [string]$_ }) -join "`n"
            throw "WSL command failed (exit $exit): $Command`nSTDOUT:`n$stdoutStr`nSTDERR:`n$stderr"
        }

        # Normalize to a single string so callers don't have to think about
        # whether bash printed one line or many.
        return (($stdout | ForEach-Object { [string]$_ }) -join "`n").TrimEnd("`r","`n")
    } finally {
        Remove-Item -ErrorAction SilentlyContinue $stderrFile
    }
}

function Copy-ToWsl {
    param(
        [Parameter(Mandatory)] [string]$WindowsPath,
        [Parameter(Mandatory)] [string]$WslPath
    )
    $winFull = (Resolve-Path $WindowsPath).Path
    $drive   = $winFull.Substring(0, 1).ToLower()
    $rest    = $winFull.Substring(2) -replace '\\', '/'
    $mntPath = "/mnt/$drive$rest"
    Invoke-WslBash "install -D -m 0644 '$mntPath' '$WslPath'" | Out-Null
}

# ============================================================================
# STEP 1: VALIDATE INPUT
# ============================================================================

Write-Step "Validating project name '$Name'"
if ($Name -notmatch '^[a-zA-Z][a-zA-Z0-9_-]{0,63}$') {
    Write-Err "Project name must start with a letter and contain only letters,"
    Write-Err "digits, hyphens or underscores (max 64 chars). Got: '$Name'"
    exit 1
}
Write-Ok "OK"

# ============================================================================
# STEP 2: CHECK WSL IS ENABLED
# ============================================================================

Write-Step "Checking WSL is enabled on this machine"
if (-not (Test-WslEnabled)) {
    Write-Err "WSL does not appear to be enabled on this machine."
    Write-Err ""
    Write-Err "This is a one-time setup that needs admin rights. Please ask"
    Write-Err "IT services to run, as administrator, in PowerShell:"
    Write-Err ""
    Write-Err "    wsl --install --no-distribution"
    Write-Err ""
    Write-Err "Then reboot. After that, re-run this script as your normal user."
    exit 2
}
Write-Ok "WSL is enabled"

# ============================================================================
# EXTRACT EMBEDDED FILES TO A TEMP DIRECTORY
# ============================================================================
# We do this upfront so all the helper scripts are available on disk before
# we start calling into WSL. They get cleaned up at the end.

$StagingDir = Join-Path $env:TEMP "lab-gpu-$([guid]::NewGuid().ToString('N').Substring(0,8))"
New-Item -ItemType Directory -Force -Path $StagingDir | Out-Null
New-Item -ItemType Directory -Force -Path "$StagingDir\linux" | Out-Null
New-Item -ItemType Directory -Force -Path "$StagingDir\templates\cuda\.vscode" | Out-Null

try {
    # Linux-side scripts (LF required!)
    Write-LfFile -Path "$StagingDir\linux\bootstrap-distro.sh" -Content $E_bootstrap_distro
    Write-LfFile -Path "$StagingDir\linux\ensure-cuda.sh"      -Content $E_ensure_cuda
    Write-LfFile -Path "$StagingDir\linux\make-project.sh"     -Content $E_make_project

    # Template files (LF too — they end up inside WSL and we want consistency)
    Write-LfFile -Path "$StagingDir\templates\cuda\CMakeLists.txt"           -Content $E_cmakelists
    Write-LfFile -Path "$StagingDir\templates\cuda\main.cu"                  -Content $E_main_cu
    Write-LfFile -Path "$StagingDir\templates\cuda\.gitignore"               -Content $E_gitignore
    Write-LfFile -Path "$StagingDir\templates\cuda\README.md"                -Content $E_readme
    Write-LfFile -Path "$StagingDir\templates\cuda\.vscode\settings.json"    -Content $E_vscode_settings
    Write-LfFile -Path "$StagingDir\templates\cuda\.vscode\extensions.json"  -Content $E_vscode_extensions
    Write-LfFile -Path "$StagingDir\templates\cuda\.vscode\tasks.json"       -Content $E_vscode_tasks
    Write-LfFile -Path "$StagingDir\templates\cuda\.vscode\launch.json"      -Content $E_vscode_launch

    # ========================================================================
    # STEP 3: ENSURE THE LabGPU DISTRO EXISTS
    # ========================================================================

    Write-Step "Checking the '$DistroName' WSL distro exists"
    if (Test-DistroExists -DistroName $DistroName) {
        Write-Ok "Distro '$DistroName' already present, reusing it"

        # Reset GPU passthrough state. A pre-existing distro session may have
        # a stale dxg connection to the Windows NVIDIA driver — caused by
        # driver updates, host suspend/resume, or just kernel <-> driver ABI
        # drift between releases. Stale dxg manifests as CUDA calls (or
        # nvidia-smi) hanging in D state with no SIGKILL recovery; the cure
        # is `wsl --shutdown` to drop and re-handshake the connection.
        # A fresh distro (the else branch) doesn't need this — it's only
        # an issue for already-running sessions.
        Write-Warn2 "Resetting GPU passthrough state (wsl --shutdown)..."
        Write-Warn2 "  Note: this also stops any other running WSL distros."
        & wsl.exe --shutdown
        if ($LASTEXITCODE -ne 0) {
            Write-Warn2 "wsl --shutdown returned exit $LASTEXITCODE (continuing anyway)"
        }
    } else {
        Write-Warn2 "Distro '$DistroName' is missing - provisioning a new one"
        Write-Warn2 "This is a one-time step and takes a few minutes."

        New-Item -ItemType Directory -Force -Path $DistroInstallDir | Out-Null

        $tarballPath = Join-Path $DistroInstallDir 'rootfs.tar.gz'
        if (-not (Test-Path $tarballPath)) {
            Write-Warn2 "Downloading Ubuntu rootfs (~300 MB)..."
            Invoke-WebRequest -Uri $DistroTarballURL -OutFile $tarballPath -UseBasicParsing
        }

        Write-Warn2 "Importing as WSL distro '$DistroName'..."
        & wsl.exe --import $DistroName $DistroInstallDir $tarballPath --version 2
        if ($LASTEXITCODE -ne 0) {
            Write-Err "wsl --import failed. Check disk space and that '$DistroInstallDir' is writable."
            exit 3
        }

        Write-Warn2 "Running first-run distro bootstrap..."
        Copy-ToWsl -WindowsPath "$StagingDir\linux\bootstrap-distro.sh" `
                   -WslPath '/root/bootstrap-distro.sh'
        Invoke-WslBash -AsRoot "chmod +x /root/bootstrap-distro.sh && /root/bootstrap-distro.sh '$env:USERNAME'" | Out-Null

        # The default-user change in /etc/wsl.conf needs a restart of the
        # distro to take effect.
        Write-Warn2 "Restarting distro to apply default-user setting..."
        & wsl.exe --terminate $DistroName | Out-Null

        Write-Ok "Distro provisioned"
    }

    # ========================================================================
    # STEP 4: ENSURE CUDA TOOLKIT IS INSTALLED
    # ========================================================================

    Write-Step "Ensuring CUDA toolkit $CudaToolkitVer + PATH wiring in '$DistroName'"

    # We unconditionally run ensure-cuda.sh — it's idempotent (the dpkg check
    # inside short-circuits the apt install, and the PATH-wiring steps use
    # tee/ln -sf which are safe to repeat). This guarantees PATH fixes get
    # re-applied even on re-runs where the package was already installed.
    Write-Warn2 "First-time install takes ~5-10 minutes; re-runs are instant."

    $wslUser = (Invoke-WslBash "whoami").Trim()
    $wslHome = "/home/$wslUser"

    Copy-ToWsl -WindowsPath "$StagingDir\linux\ensure-cuda.sh" `
               -WslPath "$wslHome/ensure-cuda.sh"
    Invoke-WslBash "chmod +x ~/ensure-cuda.sh && ~/ensure-cuda.sh '$CudaToolkitVer'"
    Write-Ok "CUDA toolkit ready"

    # ========================================================================
    # STEP 5: CREATE THE PROJECT
    # ========================================================================

    Write-Step "Creating project '$Name' in WSL"

    $wslUser = (Invoke-WslBash "whoami").Trim()
    $wslHome = "/home/$wslUser"

    Copy-ToWsl -WindowsPath "$StagingDir\linux\make-project.sh" `
               -WslPath "$wslHome/.lab-gpu/make-project.sh"

    # Pack the templates into a tar and push the whole tree across in one go.
    $templatesTar = Join-Path $env:TEMP "lab-gpu-templates-$([guid]::NewGuid()).tar"
    try {
        Push-Location "$StagingDir\templates"
        & tar.exe -cf $templatesTar --format=ustar .
        if ($LASTEXITCODE -ne 0) { throw "tar failed packing templates" }
        Pop-Location

        Copy-ToWsl -WindowsPath $templatesTar -WslPath "$wslHome/.lab-gpu/templates.tar"
        Invoke-WslBash "mkdir -p ~/.lab-gpu/templates && tar -xf ~/.lab-gpu/templates.tar -C ~/.lab-gpu/templates && rm ~/.lab-gpu/templates.tar" | Out-Null
    } finally {
        Remove-Item -ErrorAction SilentlyContinue $templatesTar
    }

    $forceFlag = if ($Force) { '--force' } else { '' }
    Invoke-WslBash "chmod +x ~/.lab-gpu/make-project.sh && ~/.lab-gpu/make-project.sh '$Name' '$Type' '$ProjectsRoot' $forceFlag"

    $projectPath = "$wslHome/$ProjectsRoot/$Name"
    Write-Ok "Project created at \\wsl.localhost\$DistroName$($projectPath -replace '/', '\')"

    # ========================================================================
    # STEP 6: LAUNCH VS CODE
    # ========================================================================

    Write-Step "Opening project in VS Code (WSL remote)"

    $codeCmd = Get-Command code -ErrorAction SilentlyContinue
    if (-not $codeCmd) {
        $codeFallback = Join-Path $env:LOCALAPPDATA 'Programs\Microsoft VS Code\bin\code.cmd'
        if (Test-Path $codeFallback) {
            $codeCmd = $codeFallback
        } else {
            Write-Warn2 "VS Code not found on PATH and not at the default user-install location."
            Write-Warn2 "Project is ready at: \\wsl.localhost\$DistroName$($projectPath -replace '/', '\')"
            Write-Warn2 "Open it manually in VS Code via 'Connect to WSL' -> '$DistroName'."
            exit 0
        }
    }

    # Use --folder-uri form. The bare `--remote wsl+X /home/...` syntax is
    # fragile on Windows: code.cmd's argv passes the positional path through
    # cmd.exe parsing, which treats a leading `/` as a switch and can drop
    # or mangle the path — landing the user in an empty workbench.
    $folderUri = "vscode-remote://wsl+$DistroName$projectPath"
    Write-Host "    Opening: $folderUri" -ForegroundColor DarkGray

    # Use Start-Process so VS Code doesn't inherit this script's stdout/stderr
    # handles. Without this, a parent shell that pipes our output (Tee-Object,
    # a CI runner, etc.) hangs forever waiting on Code.exe to close its
    # inherited handles even after this script's process has exited.
    $codePath = if ($codeCmd -is [System.Management.Automation.CommandInfo]) {
        $codeCmd.Source
    } else {
        [string]$codeCmd
    }
    Start-Process -FilePath $codePath -ArgumentList @('--folder-uri', $folderUri) | Out-Null

    Write-Ok "VS Code launched"
    Write-Host ""
    Write-Host "All set. In VS Code:" -ForegroundColor Green
    Write-Host "  1. Accept the prompt to install recommended extensions." -ForegroundColor Green
    Write-Host "  2. When CMake Tools asks for a kit, pick 'Unspecified' or 'Use CMake-detected'." -ForegroundColor Green
    Write-Host "  3. Hit F7 to build, then Shift+F5 to run." -ForegroundColor Green

} finally {
    # Clean up the staging directory.
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $StagingDir
}
